// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LitSyntaxHighlighter
{
    internal sealed partial class Vsix
    {
        public const string Id = "LitSyntaxHighlighter.915c7f19-178f-43a5-a561-eed864878830";
        public const string Name = "LitSyntaxHighlighter";
        public const string Description = @"Visual Studio extension to allow syntax highlighting when working with Lit.dev html templates.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Marc Teixeira";
        public const string Tags = "LIT, JavaScript, TypeScript, Syntax Highlighting, Highlight, Highlighting";
    }
}
